name: tests

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/lint@v2

  test:
    needs: [linting]
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Run all supported Python versions on linux
        python-version: ["3.12", "3.13", "3.14"]
        os: [ubuntu-latest]
        # Include one windows and macos run
        include:
        - os: macos-latest
          python-version: "3.14"
        - os: windows-latest
          python-version: "3.14"

    steps:
      # Run tests
      - uses: neuroinformatics-unit/actions/test-uv@8fae58caf493987de249c4aa975ffc71c55d53b7 # v3.0.0
        with:
          python-version: ${{ matrix.python-version }}
          use-headless: True
